source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire'
pod 'AlamofireObjectMapper', '~> 3.0'
pod "PagingMenuController"
pod 'Sync'
pod 'SwiftyJSON'
pod 'Kanna', '~> 1.0.0'
pod 'AlamofireImage', '~> 2.0'
